#!/usr/bin/env python
# coding: utf8

from numpy import *
import csv
import sys
import os

# Read file name from command line
if len(sys.argv) < 2:
	sys.exit("Usage:\npython\t%s myfile.txt" % sys.argv[0])
if not os.path.exists(sys.argv[1]):
	sys.exit("ERROR: File %s was not found!" % sys.argv[1])
filename = sys.argv[1]

# Load text file
data = loadtxt(filename)
# Print data
for i in range(len(data[:,0])):
	print data[i,:]
