#!/usr/bin/env python
# coding: utf8

#from numpy import *

#*****************************************
# Cycle "while"
#*****************************************

i = 0
while i<10:
	print i
	i = i + 1
i = 0
A = []

while i<10:
	A.append(i**i)
	i = i + 1
print A
