#!/usr/bin/env python
# coding: utf8

from numpy import *
import csv
import sys

filename = "mydata.txt"

#*****************************************
# Read text file (version 1)
#*****************************************

# Load text file
data = loadtxt(filename)

# Print data
for i in range(len(data[:,0])):
	print data[i,:]

#*****************************************
# Read text file (version 2)
#*****************************************

# Open data file
fd = open(filename, "r")

# Read data
reader = csv.reader(fd, delimiter="\t")

# Print data
for row in reader:
	print row
