#!/usr/bin/env python
# coding: utf8

#*****************************************
# Operator "if"
#*****************************************

for i in range(-50,51,10):
	if i<0:
		print "%i - Отрицательное" % (i)
	elif i>0:
		print "%i - Положительное" % (i)
	else:
		print "%i - Равно нулю" % (i)
